### ISSUE TITLE
How do I apply it to the game?

### ISSUE THREAD

**Issue by TAKOMAN1** [egg82/TrollCommandsPlusPlus#12]
pls help

**Comment by egg82** [comment]
I'm not quite sure what you mean by this.

To install the plugin on a Bukkit/Spigot/Paper server you would download the jar file (downloaded from the [Spigot site](https://www.spigotmc.org/resources/trollcommands-troll-your-frenemies.24237/) or [my Jenkins](https://jenkins.egg82.me/job/egg82/job/TrollCommandsPlusPlus/job/master/) depending on whether or not you are using 1.14) and drop it into the "plugins" folder. Then start (or restart) the server and type `/troll` into the chat to get additional help on how to use the plugin.

**Comment by TAKOMAN1** [comment]
I mean
I don't know how I can put this file into the game

**Comment by egg82** [comment]
That's a very vague question. What steps have you followed thus far, and what are you having trouble with? Be VERY specific.

**Comment by TAKOMAN1** [comment]
I just downloaded the file to my computer, and I don't know what to do with this file after that...
Like I downloaded it and what to do after that?

**Comment by egg82** [comment]
There's excellent guides to installing Bukkit plugins all over the internet. A few examples are [here](https://bukkit.gamepedia.com/Installing_Plugins), [here](https://www.youtube.com/watch?v=QGra7LLBlbE), [here](http://www.informatics-tech.com/how-to-install-plugins-on-a-minecraft-server.html), and [here](https://www.instructables.com/id/Minecraft-Bukkit-Server/)

**Comment by TAKOMAN1** [comment]
Thank you
