### ISSUE TITLE
pom.xml - Element artifactSet is not allowed here

### ISSUE THREAD

**Issue by TheGlitch76** [egg82/TrollCommandsPlusPlus#2]
The title says it all, and I am using Intellij Idea for my IDE

**Comment by egg82** [comment]
I've found some results for your error here:
https://www.google.com/search?q=intellij+idea+pom+%22Element%22+%22is+not+allowed+here%22&oq=intellij+idea+pom+%22Element%22+%22is+not+allowed+here%22&gs_l=psy-ab.3..35i39k1.13386.14732.0.14922.4.4.0.0.0.0.81.276.4.4.0....0...1.1.64.psy-ab..0.1.64.Wd-j7fjY51E

You may also want to try Eclipse as that's the IDE I've chosen to create the plugin in.

**Comment by TheGlitch76** [comment]
Thanks.
