### ISSUE TITLE
How do I reopen an issue?

### ISSUE THREAD

**Issue by AngelOfCreation** [egg82/TrollCommandsPlusPlus#4]
I had an issue with the plugin and we thought it was fixed but the solution egg82 told me to do didn't work. He told me to reopen it if I find the conflict but I do not know how to do that. I replyed saying it didn't work so I dont think he saw it.

**Comment by TheGlitch76** [comment]
Open a new issue, you can't mark it as closed.
Sorry this is late, but it's all I can do.

**Comment by AngelOfCreation** [comment]
Ok thank you.

**Comment by egg82** [comment]
Sorry about the delayed reply. I've been busy with some unexpected projects for the last few weeks. I've re-opened your other issue and I'll take a look at it over the next couple of days.
